url: "https://bitlyfied.github.io"
baseurl: "/your-repo-name" # Replace with your actual repository name

permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: "quote"

plugins:
  - jekyll-optional-front-matter
