url: "https://bitlyfied.github.io"
baseurl: "/quotes"

permalink: /:title/

# Use a minimal theme
theme: jekyll-theme-minimal

# Default layout for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "quote"

plugins:
  - jekyll-optional-front-matter

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
